name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install git
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.18'
    - name: Install pandoc
      run: |
        sudo apt-get install -y --no-install-recommends pandoc
    - name: Install docs dependencies
      run: |
        python -m pip install -r docs/requirements.txt
    - name: Install febio_python
      run: |
        pip install -e .
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=${PWD}:${PYTHONPATH}" >> $GITHUB_ENV
        echo $PYTHONPATH
    - name: Build HTML
      continue-on-error: true
      run: |
        pip install -e .
        python -m pip install -r docs/requirements.txt
        xvfb-run -s "-screen 0 1280x1024x24" sphinx-build -W --keep-going --color docs/source docs/build/html/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html